### ISSUE TITLE
Command Alive: Start REPL And Attach not there

### ISSUE THREAD

**Issue by habruening** [nobody-famous/alive#131] opened 2023-01-03 22:09 UTC
I just installed VS Code 1.74.2, Alive 0.3.19, Sbcl from Debian stable. I did the setup of Quicklisp and installed bordeaux-threads, usocket, cl-json and flexi-streams.

When I now start VS Code with a lisp file, there should be a command "Start REPL And Attach". But that command is not there. I see a few other commands of Alive. But without the REPL, these are not useful.

I suppose, I have to configure Alive. And I suppose, I have to download the LSP server. But the readme file does not explain this, so I did not do this. I am absolute beginner in Lisp so I have no chance to find out what to do now. The documentation should give enough information even for beginners to setup Alive.

**Comment by nobody-famous** [comment] 2023-01-03 23:16
The "Start REPL And Attach" command hasn't been there for a while. The LSP server acts as the REPL. The extension should download and start it automatically. If it's not doing that, then there's something wrong and it should have popped up some error.

**Comment by JackG-54** [comment] 2023-02-04 20:47
I'm having the same problem. When I click on View > Command Palette, I see lots of Alive: entries so I know it's installed. I also have sbcl, slime, etc. installed because they work fine when I use emacs to run code. But in VS Code + Alive, I can't actually do anything with lisp code other than edit it! 

Note: I'm running this in linux -- maybe that's the problem?

**Comment by nobody-famous** [comment] 2023-02-04 22:59
Does the side panel come up with the packages, threads, and whatnot?
If not, in the Output panel, select Alive LSP from the dropdown menu. That should show the output from SBCL.

**Comment by JackG-54** [comment] 2023-02-05 01:17
I don't see a side panel!

When I click on View > Output, it's blank.

When I select lisp code and do Alt-Shift-Enter, I get the message: _command 'alive.sendToRepl' not found_

I'm new to VS Code so that may be part of the problem.

**Comment by nobody-famous** [comment] 2023-02-05 19:22
That means it's failing to start. If you go to Output -> Alive Log what does it have?

**Comment by JackG-54** [comment] 2023-02-05 23:09
I see the following:

Activating extension
Get workspace path: undefined
No workspace folders
Using /home/jack/Lisp
Workspace Path: /home/jack/Lisp

Jack
________________________________

**Comment by JackG-54** [comment] 2023-02-05 23:17
Ah, now we're getting somewhere. I did File > Add folder to workspace ... and it seems to be working! Thanks. Should be smooth sailing from here.

**Comment by nobody-famous** [comment] 2023-02-05 23:21
Yeah, I was going to suggest opening the folder as a workspace to see if that worked. I'll look into why not having a workspace isn't working again. It used to not need a workspace, so something broke.

**Comment by lewisl** [comment] 2023-05-31 00:11
I can confirm that the whole stack does not work if the folder where you are working is not a VS Code workspace.  That is really annoying because I NEVER use workspaces (as I have no idea what purpose they serve).

**Comment by nobody-famous** [comment] 2023-06-03 22:52
This should be fixed with 0.3.23.

**Closed by nobody-famous** 2023-06-03 22:52 UTC
